const useFile = () => {
  const postFile = async (file, token) => {
    console.log('POST file');
    // create FormData object
    let formData = new FormData();
    // add file to FormData
    formData.append('file', file);

    // upload the file to file server and get the file data, use upload api endpoint
    const options = {
      method: 'POST',
      // add authorization header with token, content-type is set automatically when using FormData
      headers: {
        Authorization: `Bearer ${token}`,
      },
      body: formData,
    };
    const response = await fetch(
      `${import.meta.env.VITE_UPLOAD_SERVER}/upload`,
      options,
    );
    const parsedResponse = await response.json();
    // console.log('Raw response:', response);
    // console.log('Parsed response', parsedResponse);

    return parsedResponse.data;
  };

  const postMedia = async (file, inputs, token) => {
    console.log('POST media');
    // create a suitable object for Media API: without media_id,
    // user_id, thumbnail and created_at. All those are generated by
    // the API. See the media API documentation.
    const obj = {
      title: inputs.title,
      description: inputs.description,
      filename: file.filename,
      filesize: file.filesize,
      media_type: file.media_type,
    };

    const options = {
      method: 'POST',
      headers: {
        Authorization: `Bearer ${token}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify(obj),
    };
    // post the data to Media API and get the data as MediaResponse
    const response = await fetch(
      `${import.meta.env.VITE_MEDIA_API}/media`,
      options,
    );

    const parsedResponse = await response.json();

    // console.log(response);
    // console.log(parsedResponse);

    // return the data
    return parsedResponse;
  };

  return {
    postFile,
    postMedia,
  };
};

export default useFile;
